name: Swift CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  code-quality:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run SwiftLint
        run: swiftlint

      - name: Run SwiftFormat
        run: swiftformat .

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
