name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Schedule for Dependabot to run daily

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  code-quality:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run SwiftLint
      run: swiftlint

    - name: Run SwiftFormat
      run: swiftformat .

  sonarcloud-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
