name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Schedule for Dependabot to run daily

jobs:
  code-quality:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run SwiftLint
      run: swiftlint

    - name: Run SwiftFormat
      run: swiftformat .

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Dependabot
      uses: dependabot/fetch-metadata@v1.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Gitleaks
      uses: zricethezav/gitleaks-action@v1
