name: Swift CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest # This will use the latest macOS runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Resolve Package Dependencies
        run: xcodebuild -resolvePackageDependencies -project LithuanianLanguageLeague.xcodeproj -scheme LithuanianLanguageLeague2

      - name: List Available Simulators
        run: xcrun simctl list devices

      - name: Print Xcode version
        run: xcodebuild -version

      - name: Build and Analyze
        run: xcodebuild clean build analyze -project LithuanianLanguageLeague.xcodeproj -scheme LithuanianLanguageLeague2 -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=16.2' -allowProvisioningUpdates

      - name: Run Unit and UI Tests
        run: xcodebuild test -project LithuanianLanguageLeague.xcodeproj -scheme LithuanianLanguageLeague2 -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=16.2' -allowProvisioningUpdates

  swiftlint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run SwiftLint
        run: |
          output=$(swiftlint)
          echo "$output"
          if echo "$output" | grep -E "warning:|error:"; then
            echo "SwiftLint found style violations or errors."
            exit 1
          fi

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
