name: Swift CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest"

      - name: List available simulators
        run: |
          xcodebuild -showsdks
          xcrun simctl list devices

      - name: Build
        run: xcodebuild build -project LithuanianLanguageLeague.xcodeproj -scheme LithuanianLanguageLeague -destination "platform=iOS Simulator,OS=16.2,name=iPhone 13" -sdk iphonesimulator

      - name: Run Tests
        run: xcodebuild test -project LithuanianLanguageLeague.xcodeproj -scheme LithuanianLanguageLeague -destination "platform=iOS Simulator,OS=16.2,name=iPhone 13" -sdk iphonesimulator

  swiftlint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run SwiftLint
        run: |
          output=$(swiftlint)
          echo "$output"
          if echo "$output" | grep -E "warning:|error:"; then
            echo "SwiftLint found style violations or errors."
            exit 1
          fi

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
