name: Swift CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: sersoft-gmbh/xcodebuild-action@v3
        with:
          project: LithuanianLanguageLeague.xcodeproj
          scheme: LithuanianLanguageLeague
          destination: platform=macOS
          action: test

  swiftlint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run SwiftLint
        run: |
          output=$(swiftlint)
          echo "$output"
          if echo "$output" | grep -E "warning:|error:"; then
            echo "SwiftLint found style violations or errors."
            exit 1
          fi

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
