name: SwiftLint

on:
  pull_request:
    paths:
      - "**/*.swift"

jobs:
  lint:
    name: Lint
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: SwiftLint
        run: |
          brew install swiftlint
          swiftlint
